remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark" # רקע כהה ונקי

title: "Bar Kazir Portfolio"
url: "https://datacropsharvest.github.io"
baseurl: ""

author:
  name: "Bar Kazir"
  location: "Israel"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bar-kazir/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DataCropsHarvest"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: false # נכבה את הפרופיל בצד כדי שהכל יהיה במרכז

# הגדרות כדי למנוע מלינקדאין להתבלבל
repository: "DataCropsHarvest/datacropsharvest.github.io"
twitter_assistant: none
facebook_assistant: none

# מניעת קישור אוטומטי לפרופיל הראשי
author:
  github: "DataCropsHarvest" # רק השם, לא הלינק המלא
