# Site Settings
title: Bar Kazir| Data Analyst and Automation Specialist
locale: "en-US"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon" # סגנון כהה ומקצועי מאוד

# Site URL
url: "https://datacropsharvest.github.io"
baseurl: ""

# Profile Sidebar
author:
  name: "Bar"
  bio: "Data Scraping & Automation Expert"
  location: "Israel"
  avatar: "https://via.placeholder.com/150" # נחליף לתמונה שלך בהמשך
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DataCropsHarvest"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
