# Site Settings
title: "Bar Kazir | Data Analyst and Automation Specialist"
locale: "en-US"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "neon" # סגנון כהה יוקרתי

# GitHub Pages requires these to be set
url: "https://datacropsharvest.github.io"
baseurl: ""

# Profile Sidebar
author:
  name: "Bar"
  bio: "Automating the web, one script at a time."
  location: "Israel"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DataCropsHarvest"

# Mandatory Plugins for Minimal Mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# Build Settings
include: ["_pages", "_data"]
exclude: ["Gemfile", "Gemfile.lock"]

# Setup Portfolio Layout
defaults:
  - scope:
      path: ""
    values:
      layout: "single"
      author_profile: true
